### ISSUE TITLE
Compiling Errors

### ISSUE THREAD

**Issue by martdob** [melowntech/vts-browser-cpp-build-wrapper#1]
Hi, I followed the instruction exactly according the instructions. I am compiling the VTS Plugin under Windows 10 with the newest git, Phyton. Perl is not on my mashine. Is Perl needed? There are some erros saying that Perl is missing on my mashine.

-- Could NOT find Perl (missing: PERL_EXECUTABLE)
-- Perl not found, testing disabled.
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Looking for getch in ws2_32;
-- Looking for getch in ws2_32; - found
-- Looking for getch in winmm;ws2_32
-- Looking for getch in winmm;ws2_32 - found
-- Looking for idn2_lookup_ul in idn2;winmm;ws2_32;advapi32;crypt32
-- Looking for idn2_lookup_ul in idn2;winmm;ws2_32;advapi32;crypt32 - not found
-- Could NOT find LibSSH2 (missing: LIBSSH2_INCLUDE_DIR LIBSSH2_LIBRARY)
-- Performing Test USE_UNIX_SOCKETS
-- Performing Test USE_UNIX_SOCKETS - Failed
-- Looking for include file windows.h
-- Looking for include file windows.h - found
-- Looking for include files windows.h, winsock.h

**Comment by malytomas** [comment]
perl is not needed. could you send complete output? the snippet you sent seems ok.
