### ISSUE TITLE
Missing files in the Externals directory

### ISSUE THREAD

**Issue by 980591032** [melowntech/vts-browser-cpp-build-wrapper#2]
Excuse me , I tried to build wrappers on Windows , But I couldn't build it successfully, and there were many mistakes.  Could you give me some details?

**Comment by malytomas** [comment]
Hi,
build instructions are in the [readme](https://github.com/melowntech/vts-browser-cpp-build-wrapper/blob/master/README.md). Make sure you have all the required software and correct configuration.

If you want any further help, you have to write the steps that you do and what are the issues you have. Be very specific. Copy the relevant parts from the logs. Also write version of the software that you use (windows, visual studio, cmake, python, etc.).

**Comment by 980591032** [comment]
I am very happy to see you replying.
Now I also wrote a configuration file based on your configuration file, putting it into unity and causing unity to crash.
I want to ask what is the requirement for the configuration file?
or Whether the wrapper is too low or not.
Looking forward to your reply.
thank you very much.
------------------ 原始邮件 ------------------
发件人: "Tomáš Malý"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 下午4:16
收件人: "melowntech/vts-browser-cpp-build-wrapper"<vts-browser-cpp-build-wrapper@noreply.github.com>;
抄送: "往后余生-风雪是你"<980591032@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [melowntech/vts-browser-cpp-build-wrapper] Build Wrapper Faild(#2)




Hi,
 build instructions are in the readme. Make sure you have all the required software and correct configuration.
 
If you want any further help, you have to write the steps that you do and what are the issues you have. Be very specific. Copy the relevant parts from the logs. Also write version of the software that you use (windows, visual studio, cmake, python, etc.).

**Comment by malytomas** [comment]
I am sorry, but I do not follow you.
This is the first time that you mention unity. If you are building VTS for unity, then use https://github.com/melowntech/vts-browser-unity-plugin
Have you tried the https://assetstore.unity.com/packages/tools/terrain/vts-landscape-streaming-plugin-125885 ? This is much simpler to set up.
Also what configuration file are you talking about?

**Comment by 980591032** [comment]
I'd like to ask you for help.
Do you have the latest version of dll?  
I have encountered a lot of problems in the cmake process, 
and I have worked hard for a long time and have not solved it. 
If you have the latest dll, can you send me a copy?
Thank you very much！




------------------ 原始邮件 ------------------
发件人: "Tomáš Malý"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 下午5:21
收件人: "melowntech/vts-browser-cpp-build-wrapper"<vts-browser-cpp-build-wrapper@noreply.github.com>;
抄送: "自由如风"<980591032@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [melowntech/vts-browser-cpp-build-wrapper] Build Wrapper Faild(#2)




I am sorry, but I do not follow you.
 This is the first time that you mention unity. If you are building VTS for unity, then use https://github.com/melowntech/vts-browser-unity-plugin
 Have you tried the https://assetstore.unity.com/packages/tools/terrain/vts-landscape-streaming-plugin-125885 ? This is much simpler to set up.
 Also what configuration file are you talking about?

**Comment by malytomas** [comment]
I plan to deploy a new version of the plugin on asset store in few weeks.
In the meantime, I would like to understand your problem, so that we can perhaps improve the documentation.

**Comment by 980591032** [comment]
First declare that I am using cmake for the first time and I will download the
 https://github.com/melowntech/vts-browser-cpp-build-wrapper/tree/12528e26da24a6382df79645268212d487f9745d 
project under this URL via github. Compiling with cmakegui will appear Many non-existent phenomena, the following is a screenshot


Maybe it’s my lack of experience. I don’t know what to ask for these errors, so I’d like to ask,
I hope to hear from you. If you have time, we can keep in touch at any time. 
Thank you very much.wish you a happy life
------------------ 原始邮件 ------------------
发件人: "Tomáš Malý"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 晚上7:06
收件人: "melowntech/vts-browser-cpp-build-wrapper"<vts-browser-cpp-build-wrapper@noreply.github.com>;
抄送: "自由如风"<980591032@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [melowntech/vts-browser-cpp-build-wrapper] Build Wrapper Faild(#2)




I plan to deploy a new version of the plugin on asset store in few weeks.
 In the meantime, I would like to understand your problem, so that we can perhaps improve the documentation.

**Comment by malytomas** [comment]
I understand the problem now.
Do not download from github.
Use git instead. Git will also download many other files from many other repositories (called submodules).


Download git from here: https://gitforwindows.org/
During installation, enable using symlinks (symbolic file links)!
Restart the computer.
Right click on an empty folder and choose _git bash here_.
In the console do:
```bash
git clone --recursive https://github.com/melowntech/vts-browser-cpp-build-wrapper.git
cd vts-browser-cpp-build-wrapper
mkdir build
cd build
cmake -G"Visual Studio 15 2017 Win64" ..
cmake --build . --config relwithdebinfo
```

**Comment by malytomas** [comment]
Alternatively, you may use the cmakegui. Just make sure that you use git to fetch all the files.

**Comment by 980591032** [comment]
Thank you very much for your reply. I'll try it right away. I hope to have a surprise. Thank you.







------------------ 原始邮件 ------------------
发件人: "Tomáš Malý"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 晚上7:54
收件人: "melowntech/vts-browser-cpp-build-wrapper"<vts-browser-cpp-build-wrapper@noreply.github.com>;
抄送: "自由如风"<980591032@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [melowntech/vts-browser-cpp-build-wrapper] Build Wrapper Faild(#2)




Alternatively, you may use the cmakegui. Just make sure that you use git to fetch all the files.

**Comment by 980591032** [comment]
Hello, I tried it your way and found the following problem. Please take a look at the screenshot.


How should this problem be solved? Trouble you.


------------------ 原始邮件 ------------------
发件人: "Tomáš Malý"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 晚上7:54
收件人: "melowntech/vts-browser-cpp-build-wrapper"<vts-browser-cpp-build-wrapper@noreply.github.com>;
抄送: "自由如风"<980591032@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [melowntech/vts-browser-cpp-build-wrapper] Build Wrapper Faild(#2)




Alternatively, you may use the cmakegui. Just make sure that you use git to fetch all the files.

**Comment by malytomas** [comment]
There is no screenshot.

**Comment by 980591032** [comment]
I'm very sorry. Please see the attachment.




------------------ 原始邮件 ------------------
发件人: "Tomáš Malý"<notifications@github.com>;
发送时间: 2019年9月6日(星期五) 下午3:46
收件人: "melowntech/vts-browser-cpp-build-wrapper"<vts-browser-cpp-build-wrapper@noreply.github.com>;
抄送: "自由如风"<980591032@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [melowntech/vts-browser-cpp-build-wrapper] Build Wrapper Faild(#2)




There is no screenshot.

**Comment by malytomas** [comment]
To add an image add it at github page directly. I cannot see attachments to email replies.
