### ISSUE TITLE
git clone: file names too long

### ISSUE THREAD

**Issue by 980591032** [melowntech/vts-browser-cpp-build-wrapper#3]
fatal: cannot create directory at 'autotest/gdrivers/data/fake_sentinel2_l2a_MSIL2A/S2A_MSIL2A_20180818T094031_N0208_R036_T34VFJ_20180818T120345.SAFE/GRANULE/L2A_T34VFJ_A016478_20180818T094030/IMG_DATA/R10m': Filename too long
Unable to checkout '825662d03251faac29c5c683c74694ba56124e90' in submodule path 'externals/gdal/gdal'

**Comment by malytomas** [comment]
Apply this configuration:
```bash
git config --system core.longpaths true
```

See this for more information:
https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows
