### ISSUE TITLE
VTS browser for the latest versions of Mac OS.

### ISSUE THREAD

**Issue by SukanyaGavhane** [melowntech/vts-browser-cpp-build-wrapper#5]
We observed that the latest versions of **Mac OS**(Ex: Mojave) deprecates **OpenGL** and must have **Metal** to provide graphics hardware support.

Considering that we have following queries,

**1. Does the latest version of the VTS browser provide support for an updated Mac OS versions ?**

**2. The latest version of VTS for Mac OS is developed based on OpenGL or Metal?**

**3. If it is based on Metal, does it provide any leverage for OpenGL?**

**Comment by malytomas** [comment]
https://github.com/melowntech/vts-browser-cpp/issues/10

Double posting does not help.
