### ISSUE TITLE
Compile Failed

### ISSUE THREAD

**Issue by HanochZhu** [melowntech/vts-browser-cpp-build-wrapper#6]
Hi MelownTech:
I tried to compile vts-wrapper, but failed.

I turn on the developer mode in windows.

and execute command line as follow:
```
git clone --recursive https://github.com/melowntech/vts-browser-cpp-build-wrapper.git
cd vts-browser-cpp-build-wrapper
mkdir build
cd build
cmake -G"Visual Studio 15 2017 Win64" ..
```
I used powershell in admin, get the following error info:
```
CMake Error at externals/browser/browser/CMakeLists.txt:10 (include):
  include could not find load file:

    buildsys/cmake/buildsys.cmake


CMake Error at externals/browser/browser/CMakeLists.txt:11 (enable_hidden_visibility):
  Unknown CMake command "enable_hidden_visibility".


-- Configuring incomplete, errors occurred!
See also "D:/GitHub/vts-browser-cpp-build-wrapper/vts-browser-cpp-build-wrapper/build/CMakeFiles/CMakeOutput.log".
See also "D:/GitHub/vts-browser-cpp-build-wrapper/vts-browser-cpp-build-wrapper/build/CMakeFiles/CMakeError.log".
```

**Comment by malytomas** [comment]
Please, make sure that you have enabled symlinks during git installation.
![](https://aws1.discourse-cdn.com/github/original/2X/2/271993b6cebb4de88b38a4ca652d7f701c5d4ce2.png)

**Comment by HanochZhu** [comment]
Hi malytomas:
I have turn on enable symbolic links when install git bash. But this issue still exist. Is there any configuration in windows?

![image](https://user-images.githubusercontent.com/26645907/86320450-82c8b100-bc69-11ea-8f0a-b7221094641e.png)

**Comment by malytomas** [comment]
Please create a new empty folder and run the following script in it in the git bash (mingw console):

```bash
(
echo "versions:" &&
git --version &&
cmake --version &&
echo "git:" &&
git clone https://github.com/melowntech/vts-browser-cpp-build-wrapper.git vts-builder &&
cd vts-builder &&
git submodule update --init --recursive &&
echo "ls:" &&
ls -l externals/browser/browser/buildsys/cmake &&
echo "build" &&
mkdir build &&
cd build &&
cmake -G"Visual Studio 15 2017" -Ax64 ..
) 2>&1 | tee vts-build-output.txt
```

Please attach the vts-build-output.txt here afterwards.

**Comment by HanochZhu** [comment]
Hi malytomas:
I have successed generate vs project.It's because I have not use admin mode.
I want to get altitude according to longtitude and latitude. Is there any way to get altitude in vts plugin instead of modify source code. This is why I want to compile vts-browser-cpp project.

Thanks.

**Comment by malytomas** [comment]
> I have successed generate vs project.It's because I have not use admin mode.

Admin rights should not be necessary if the developer mode is enabled. What version and build of windows do you use? Do you have up-to-date git?

-----

> I want to get altitude according to longtitude and latitude. Is there any way to get altitude in vts plugin instead of modify source code. This is why I want to compile vts-browser-cpp project.

I have recently answered similar question in an email. Was that, by any chance, you? Have you not get the email?

Anyway, take a look at this function:
https://github.com/melowntech/vts-browser-unity-plugin/blob/ee67b39bd6f4fbf5f9379d40f7582629b72f0304/src/Vts/Scripts/VtsMap.cs#L84
It allows conversions between unity world space and vts navigation srs.

Furthermore, you can use:
https://github.com/melowntech/vts-browser-cpp/blob/29de53e543c7f1f6845d05b642f0765388a8a5bc/browser/src/vts-libbrowser-cs/Map.cs#L175
to convert between any two srs that are defined in the mapconfig.

**Comment by HanochZhu** [comment]
Ah , Is me.
I did two things this time. I turn off my security software and use admin right.
Thanks for you answer. And I have received you email. I am confusion. Can convert function get the altitude from longtitude and latitude?  If it is capable, which type of sys should choice. Could you give any document about what Sys type means?
Thanks!

**Comment by malytomas** [comment]
Reference frame and SRS is explained in here:
https://vts-geospatial.org/reference/concepts.html

As stated in the email, acquiring _altitude of a surface above ellipsoid_ for arbitrary places is not possible in vts because it would require downloading additional files. 

The VtsNavigationToUnity can be used to convert any (lat, lon, zero) into unity world space, giving you a point with zero altitude above the ellipsoid.

**Comment by HanochZhu** [comment]
Is there any way to get the altitude if we do not care about network consume. Do we need modify the source code?  Thanks!

**Comment by malytomas** [comment]
> Is there any way to get the altitude if we do not care about network consume. Do we need modify the source code? Thanks!

You can place collider probe with small radius and read the properties from it.
It provides altitude of the probe over ellipsoid and altitude of the probe over surface.
(The properties are not currently exposed in the plugin but are available in c#. You do not have to modify c++ code.)

**Comment by HanochZhu** [comment]
Do you mean that we could generate probe like sphere collider along the surface of  each tile. Sorry, I dont understand how to imple it. In face, we want to generate a symbol on arbitray place like a mountain top. But we can only get the longtitude and latitude of a landmark.

 Could you give any clue that how to solve it. Thanks a lot!

**Comment by malytomas** [comment]
I meant an object with VtsColliderProbe script attached to it.

However, if you have a lot of landmarks, that approach would be inefficient and you would probably do better to acquire the altitudes somewhere outside vts.

**Comment by HanochZhu** [comment]
Great! I will try it.
By the way, I find there is a function in altitude.cpp.

![image](https://user-images.githubusercontent.com/26645907/86366926-f9879d80-bcad-11ea-8f15-b189a516aa5c.png)

Could it get the altitude?  It might be a last question I want know.

Thanks！

**Comment by malytomas** [comment]
CameraImpl::getSurfaceOverEllipsoid is internal function and is not available in the api.
It is used inside the collider probe.

**Comment by HanochZhu** [comment]
cool! I think it is enough to use collider probe. Thanks!

**Comment by HanochZhu** [comment]
Sorry, I have other question.
Should I replace the vts-browser.dll in default vts plugin after I compilier vts plugin successful?

I replace it now but get "EntryPointNotFoundException" exception.
```
EntryPointNotFoundException: vtsMapRenderInitialize
vts.Map.RenderInitialize () (at Assets/Vts/Scripts/Browser/Map.cs:155)
VtsMap.Awake () (at Assets/Vts/Scripts/VtsMap.cs:48)
```

**Comment by malytomas** [comment]
The vts-browser.dll has to be the one corresponding to the plugin.

If you have plugin downloaded from unity store, use the dll that is bundled with it.

If you want to build your own dll, use the plugin code from this repository:
https://github.com/melowntech/vts-browser-unity-plugin
and use the dll that you build from the same repository.

**Comment by HanochZhu** [comment]
Cool, Thank you!
VTS-plugins is a really great toolkit for unity.

**Comment by HanochZhu** [comment]
Hi malytomas, 
I tried to build and replace the vts-browser.dll, but unity prompt :
```
EntryPointNotFoundException: vtsMapRenderInitialize
vts.Map.RenderInitialize () (at Assets/Vts/Scripts/Browser/Map.cs:155)
VtsMap.Awake () (at Assets/Vts/Scripts/VtsMap.cs:48)
```
Is there any thing wrong when i build this library? Thanks.
